Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),
]

Proyecto/tienda/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('user/', views.user_page, name='user_page'),  
    path('menu/', views.menu, name='menu'),            
    path('users-list', views.users_list, name='users_list'),  
    path('admin', views.admin, name='admin'), 
    path('crear_producto/', views.product_create, name='product_create'),
    path('product/<int:pk>/', views.product_detail, name='product-detail'),
    path('eliminar-usuario/<int:user_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('inventario/', views.product_list, name='inventario'),  # Utiliza el mismo método para ambos tipos de usuarios
    path('cart/detail/', views.cart_detail, name='cart-detail'),
    path('cart/add/<int:pk>/', views.cart_add, name='cart-add'),
    path('cart/remove/<int:pk>/', views.cart_remove, name='cart-remove'),
    path('cart/update/<int:pk>/', views.cart_update, name='cart-update'),
    path('editar-usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('editar-producto/<int:product_id>/', views.editar_producto, name='editar_producto'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('register/', views.register, name='register'), 

    





]

Proyecto/tienda/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    @property
    def category_name(self):
        return self.category.name
    

class Cart(models.Model):
    pass

    class Meta:
        verbose_name = 'Carrito de compra'
        verbose_name_plural = 'Carritos de compra'
    def __str__(self):
        return f'Carrito de compra {self.id}'    

    @property
    def total_items(self):
        return self.items.count()
        
    @property
    def total_price(self):
        return sum([item.total_price for item in self.items.all()])

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        verbose_name = 'Carrito de compra'
        verbose_name_plural = 'Carritos de compra'


    def __str__(self):
        return self.product.name

    @property
    def total_price(self):
        return self.product.price * self.quantity

Proyecto/tienda/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class LoginForms(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Las contraseñas no son iguales')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.fields['username'].disabled = True  # Bloquea la edición del nombre de usuario

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError('Este correo electrónico ya está en uso.')
        return email
    
class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price','category']
    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        self.fields['name'].disabled = True #Bloqueamos la edición del nombre del producto

 

Proyecto/tienda/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import *
from django.contrib.auth.models import User
from .models import *
from .utils import get_cart

def user_login(request):
    if request.method == 'POST':
        form = LoginForms(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)    
                    if user.is_superuser:  # Verifica si el usuario es administrador
                        return redirect('admin')
                    else:
                        return redirect('user_page')  # Redirige a la página de usuario común
                else:
                    return HttpResponse('Usuario no autenticado')
            else:
                return HttpResponse('Credenciales inválidas')
    else:
        form = LoginForms()
    return render(request, 'registration/login.html', {'form': form})

@login_required
def admin(request):
    if request.user.is_authenticated:
        return redirect('users_list')
    else:
        return render(request, 'tienda/admin.html', {})


@login_required
def user_page(request):
    if request.user.is_authenticated:
        # Si el usuario ha iniciado sesión, redirige al menú
        return redirect('menu')
    else:
        return render(request, 'usuario/usuario.html', {})

@login_required
def user_logout(request):
    logout(request)
    return redirect('login')


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password']
            )
            new_user.save()
            return render(request, 'tienda/register_done.html',
                          {'new_user':new_user}
            )
        
    
    else:
        user_form = UserRegistrationForm()
    return render(request, 'tienda/register.html', {'user_form': user_form})


def users_list(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request,'tienda/admin.html', context)


@login_required
def editar_usuario(request, user_id):
    # Obtener el usuario a editar o mostrar un error 404 si no existe
    user = get_object_or_404(User, id=user_id)
    
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users_list')
    else:
        form = UserEditForm(instance=user)
    
    return render(request, 'tienda/editar_usuario.html', {'form': form})

@login_required
def eliminar_usuario(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        user.delete()
        return redirect('admin')
    return render(request, 'tienda/confirm_delete.html', {'user': user})
@login_required
def product_list(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    if request.user.is_superuser:
        template_name = 'tienda/inventario.html'
    else:
        template_name = 'usuario/inventario_user.html'
    context = {
        'categories' : categories,
        'products' : products
    }
    return render(request, template_name, context)


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'product': product
    }
    return render(request, 'usuario/detail.html', context)


@login_required
def product_create(request):
    if request.method == ('POST'):
        name = request.POST.get('name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        category = request.POST.get('category')
        category = Category.objects.get(id = category)
        product = Product.objects.create(
            name = name,
            description = description,
            price = price,
            category = category
        )   
        return redirect('inventario')
    context = {
        'categories' : Category.objects.all()
    }
    return render(request, 'tienda/crear_producto.html', context)

@login_required
def editar_producto(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.user.is_superuser:
        template_name = 'tienda/editar_producto.html'
    else:
        template_name = 'usuario/editar_producto_user.html'

    if request.method == 'POST':
        form = ProductEditForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('inventario' if request.user.is_superuser else 'inventario_user')
    else:
        form = ProductEditForm(instance=product)

    return render(request, template_name, {'form': form})     

#Metodos para el usuario

@login_required
def menu(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories' : categories,
        'products' : products
    }
    return render(request, 'usuario/usuario.html', context)



@login_required
def detail_list(request):
    cart = get_cart(request)
    context = {
        'cart': cart
    }

    return render(request, 'cart/detail.html', context)

def cart_detail(request):
    cart = get_cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'cart/detail.html', context)


@login_required
def cart_add(request, pk):
    product = get_object_or_404(Product, pk=pk)
    cart = get_cart(request)
    quantity = request.POST.get('quantity')
    cart_item, created = CartItem.objects.get_or_create(
        cart=cart,
        product=product,
        defaults={'quantity': quantity}
    )
    if not created:
        cart_item.quantity += int(quantity)
        cart_item.save()
    return redirect('cart-detail')


@login_required
def cart_remove(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk)
    cart_item.delete()
    return redirect('cart-detail')

@login_required
def cart_update(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk)
    quantity = request.POST.get('quantity')
    cart_item.quantity = quantity
    cart_item.save()
    return redirect('cart-detail')

Proyecto/tienda/templates/usuario/detail.html
{% extends "base_users.html" %}
{% block title %}Detalle de Carrito{% endblock %}
{% block content %}


<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 text-center">
            <img src="https://www.odoo.com/web/image/res.users/1072846/image_1024?unique=3f33558" alt="Generic product" class="img-fluid">
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <span class="text-primary float-end">${{ product.price }}.00</span>
                    <h5>{{ product }}</h5>
                    <p>{{ product.description }}</p>
                    <form action="{% url 'cart-add' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="number" name="quantity" class="form-control" value="1">
                            <button type="submit" class="btn btn-primary">Add to cart</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Proyecto/tienda/templates/usuario/editar_producto_user.html
{% extends "base_users.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
  <h1>Dashboard</h1>
  <p>Welcome to your dashboard.</p>
  <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Logout</button>
  </form>
  <h1>Editar Usuario</h1>
  <form method="post">
      {% csrf_token %}
      <label for="id_name">Nombre del platillo:</label><br>
      {{ form.name }}<br><br>

      <label for="id_description">Descripción:</label><br>
      {{ form.description }}<br><br>

      <label for="id_price">Precio:</label><br>
      {{ form.price }}<br><br>

      <label for="id_category">Categoría</label><br>
      {{ form.category }}<br><br>

      <button type="submit">Guardar cambios</button>
  </form>
{% endblock %}
</html>

Proyecto/tienda/templates/usuario/inventario_user.html
{% extends "base_users.html" %}
{% block title %}Control de Inventario{% endblock %}
{% block content %}

<h1>Control de inventario</h1>
  <p>Welcome to your dashboard.</p>
  <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Logout</button>
  </form>

  <div class="container mt-5">
    <div class="row">
      {% for product in products %}
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <span class="text-primary float-end">Precio: ${{ product.price }}</span>
            <h5>{{ product }}</h5>
            <p>{{ product.description }}</p>
            <a href="{% url 'editar_producto' product.pk %}" class="btn btn-primary">Editar</a>
          </div>
        </div>
      </div>  
      {% endfor %}
    </div>
  </div>
  <a href="{% url 'product_create'%}" class="btn btn-primary">Añadir</a>

{% endblock %}

Proyecto/tienda/templates/usuario/usuario.html
{% extends "base_users.html" %}
{% block title %}Control de Inventario{% endblock %}
{% block content %}

<h1>Menú del día</h1>
  <p>Welcome to your dashboard.</p>
  <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Logout</button>
  </form>

  <div class="container mt-5">
    <div class="row">
        {% for product in products %}
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <span class="text-primary float-end">${{ product.price }}.00</span>
                    <h5>{{ product }}</h5>
                    <p>{{ product.description }}</p>
                    <a href="{% url 'product-detail' product.id %}" class="btn btn-primary">Comprar</a>
                    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}